// Code generated by ent, DO NOT EDIT.

package expense

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the expense type in the database.
	Label = "expense"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChatID holds the string denoting the chat_id field in the database.
	FieldChatID = "chat_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPaidBy holds the string denoting the paid_by field in the database.
	FieldPaidBy = "paid_by"
	// FieldPaidByName holds the string denoting the paid_by_name field in the database.
	FieldPaidByName = "paid_by_name"
	// FieldForOther holds the string denoting the for_other field in the database.
	FieldForOther = "for_other"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the expense in the database.
	Table = "expenses"
)

// Columns holds all SQL columns for expense fields.
var Columns = []string{
	FieldID,
	FieldChatID,
	FieldAmount,
	FieldDescription,
	FieldPaidBy,
	FieldPaidByName,
	FieldForOther,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultForOther holds the default value on creation for the "for_other" field.
	DefaultForOther bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Expense queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChatID orders the results by the chat_id field.
func ByChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPaidBy orders the results by the paid_by field.
func ByPaidBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidBy, opts...).ToFunc()
}

// ByPaidByName orders the results by the paid_by_name field.
func ByPaidByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidByName, opts...).ToFunc()
}

// ByForOther orders the results by the for_other field.
func ByForOther(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForOther, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
