// Code generated by ent, DO NOT EDIT.

package expense

import (
	"bill-buddy/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldID, id))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldChatID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldAmount, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldDescription, v))
}

// PaidBy applies equality check predicate on the "paid_by" field. It's identical to PaidByEQ.
func PaidBy(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldPaidBy, v))
}

// PaidByName applies equality check predicate on the "paid_by_name" field. It's identical to PaidByNameEQ.
func PaidByName(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldPaidByName, v))
}

// ForOther applies equality check predicate on the "for_other" field. It's identical to ForOtherEQ.
func ForOther(v bool) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldForOther, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldCreatedAt, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...int64) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...int64) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldChatID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldAmount, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Expense {
	return predicate.Expense(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Expense {
	return predicate.Expense(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Expense {
	return predicate.Expense(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Expense {
	return predicate.Expense(sql.FieldContainsFold(FieldDescription, v))
}

// PaidByEQ applies the EQ predicate on the "paid_by" field.
func PaidByEQ(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldPaidBy, v))
}

// PaidByNEQ applies the NEQ predicate on the "paid_by" field.
func PaidByNEQ(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldPaidBy, v))
}

// PaidByIn applies the In predicate on the "paid_by" field.
func PaidByIn(vs ...int64) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldPaidBy, vs...))
}

// PaidByNotIn applies the NotIn predicate on the "paid_by" field.
func PaidByNotIn(vs ...int64) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldPaidBy, vs...))
}

// PaidByGT applies the GT predicate on the "paid_by" field.
func PaidByGT(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldPaidBy, v))
}

// PaidByGTE applies the GTE predicate on the "paid_by" field.
func PaidByGTE(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldPaidBy, v))
}

// PaidByLT applies the LT predicate on the "paid_by" field.
func PaidByLT(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldPaidBy, v))
}

// PaidByLTE applies the LTE predicate on the "paid_by" field.
func PaidByLTE(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldPaidBy, v))
}

// PaidByNameEQ applies the EQ predicate on the "paid_by_name" field.
func PaidByNameEQ(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldPaidByName, v))
}

// PaidByNameNEQ applies the NEQ predicate on the "paid_by_name" field.
func PaidByNameNEQ(v string) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldPaidByName, v))
}

// PaidByNameIn applies the In predicate on the "paid_by_name" field.
func PaidByNameIn(vs ...string) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldPaidByName, vs...))
}

// PaidByNameNotIn applies the NotIn predicate on the "paid_by_name" field.
func PaidByNameNotIn(vs ...string) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldPaidByName, vs...))
}

// PaidByNameGT applies the GT predicate on the "paid_by_name" field.
func PaidByNameGT(v string) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldPaidByName, v))
}

// PaidByNameGTE applies the GTE predicate on the "paid_by_name" field.
func PaidByNameGTE(v string) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldPaidByName, v))
}

// PaidByNameLT applies the LT predicate on the "paid_by_name" field.
func PaidByNameLT(v string) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldPaidByName, v))
}

// PaidByNameLTE applies the LTE predicate on the "paid_by_name" field.
func PaidByNameLTE(v string) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldPaidByName, v))
}

// PaidByNameContains applies the Contains predicate on the "paid_by_name" field.
func PaidByNameContains(v string) predicate.Expense {
	return predicate.Expense(sql.FieldContains(FieldPaidByName, v))
}

// PaidByNameHasPrefix applies the HasPrefix predicate on the "paid_by_name" field.
func PaidByNameHasPrefix(v string) predicate.Expense {
	return predicate.Expense(sql.FieldHasPrefix(FieldPaidByName, v))
}

// PaidByNameHasSuffix applies the HasSuffix predicate on the "paid_by_name" field.
func PaidByNameHasSuffix(v string) predicate.Expense {
	return predicate.Expense(sql.FieldHasSuffix(FieldPaidByName, v))
}

// PaidByNameEqualFold applies the EqualFold predicate on the "paid_by_name" field.
func PaidByNameEqualFold(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEqualFold(FieldPaidByName, v))
}

// PaidByNameContainsFold applies the ContainsFold predicate on the "paid_by_name" field.
func PaidByNameContainsFold(v string) predicate.Expense {
	return predicate.Expense(sql.FieldContainsFold(FieldPaidByName, v))
}

// ForOtherEQ applies the EQ predicate on the "for_other" field.
func ForOtherEQ(v bool) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldForOther, v))
}

// ForOtherNEQ applies the NEQ predicate on the "for_other" field.
func ForOtherNEQ(v bool) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldForOther, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Expense) predicate.Expense {
	return predicate.Expense(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Expense) predicate.Expense {
	return predicate.Expense(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Expense) predicate.Expense {
	return predicate.Expense(sql.NotPredicates(p))
}
