// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-buddy/ent/expense"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExpenseCreate is the builder for creating a Expense entity.
type ExpenseCreate struct {
	config
	mutation *ExpenseMutation
	hooks    []Hook
}

// SetChatID sets the "chat_id" field.
func (_c *ExpenseCreate) SetChatID(v int64) *ExpenseCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ExpenseCreate) SetAmount(v float64) *ExpenseCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ExpenseCreate) SetDescription(v string) *ExpenseCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableDescription(v *string) *ExpenseCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPaidBy sets the "paid_by" field.
func (_c *ExpenseCreate) SetPaidBy(v int64) *ExpenseCreate {
	_c.mutation.SetPaidBy(v)
	return _c
}

// SetPaidByName sets the "paid_by_name" field.
func (_c *ExpenseCreate) SetPaidByName(v string) *ExpenseCreate {
	_c.mutation.SetPaidByName(v)
	return _c
}

// SetForOther sets the "for_other" field.
func (_c *ExpenseCreate) SetForOther(v bool) *ExpenseCreate {
	_c.mutation.SetForOther(v)
	return _c
}

// SetNillableForOther sets the "for_other" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableForOther(v *bool) *ExpenseCreate {
	if v != nil {
		_c.SetForOther(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExpenseCreate) SetCreatedAt(v time.Time) *ExpenseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableCreatedAt(v *time.Time) *ExpenseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ExpenseMutation object of the builder.
func (_c *ExpenseCreate) Mutation() *ExpenseMutation {
	return _c.mutation
}

// Save creates the Expense in the database.
func (_c *ExpenseCreate) Save(ctx context.Context) (*Expense, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExpenseCreate) SaveX(ctx context.Context) *Expense {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpenseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpenseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExpenseCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := expense.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.ForOther(); !ok {
		v := expense.DefaultForOther
		_c.mutation.SetForOther(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := expense.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExpenseCreate) check() error {
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "Expense.chat_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Expense.amount"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Expense.description"`)}
	}
	if _, ok := _c.mutation.PaidBy(); !ok {
		return &ValidationError{Name: "paid_by", err: errors.New(`ent: missing required field "Expense.paid_by"`)}
	}
	if _, ok := _c.mutation.PaidByName(); !ok {
		return &ValidationError{Name: "paid_by_name", err: errors.New(`ent: missing required field "Expense.paid_by_name"`)}
	}
	if _, ok := _c.mutation.ForOther(); !ok {
		return &ValidationError{Name: "for_other", err: errors.New(`ent: missing required field "Expense.for_other"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Expense.created_at"`)}
	}
	return nil
}

func (_c *ExpenseCreate) sqlSave(ctx context.Context) (*Expense, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExpenseCreate) createSpec() (*Expense, *sqlgraph.CreateSpec) {
	var (
		_node = &Expense{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(expense.Table, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ChatID(); ok {
		_spec.SetField(expense.FieldChatID, field.TypeInt64, value)
		_node.ChatID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(expense.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(expense.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.PaidBy(); ok {
		_spec.SetField(expense.FieldPaidBy, field.TypeInt64, value)
		_node.PaidBy = value
	}
	if value, ok := _c.mutation.PaidByName(); ok {
		_spec.SetField(expense.FieldPaidByName, field.TypeString, value)
		_node.PaidByName = value
	}
	if value, ok := _c.mutation.ForOther(); ok {
		_spec.SetField(expense.FieldForOther, field.TypeBool, value)
		_node.ForOther = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(expense.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ExpenseCreateBulk is the builder for creating many Expense entities in bulk.
type ExpenseCreateBulk struct {
	config
	err      error
	builders []*ExpenseCreate
}

// Save creates the Expense entities in the database.
func (_c *ExpenseCreateBulk) Save(ctx context.Context) ([]*Expense, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Expense, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExpenseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExpenseCreateBulk) SaveX(ctx context.Context) []*Expense {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpenseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpenseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
