// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-buddy/ent/expense"
	"bill-buddy/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExpenseUpdate is the builder for updating Expense entities.
type ExpenseUpdate struct {
	config
	hooks    []Hook
	mutation *ExpenseMutation
}

// Where appends a list predicates to the ExpenseUpdate builder.
func (_u *ExpenseUpdate) Where(ps ...predicate.Expense) *ExpenseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *ExpenseUpdate) SetChatID(v int64) *ExpenseUpdate {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillableChatID(v *int64) *ExpenseUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *ExpenseUpdate) AddChatID(v int64) *ExpenseUpdate {
	_u.mutation.AddChatID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ExpenseUpdate) SetAmount(v float64) *ExpenseUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillableAmount(v *float64) *ExpenseUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ExpenseUpdate) AddAmount(v float64) *ExpenseUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExpenseUpdate) SetDescription(v string) *ExpenseUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillableDescription(v *string) *ExpenseUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPaidBy sets the "paid_by" field.
func (_u *ExpenseUpdate) SetPaidBy(v int64) *ExpenseUpdate {
	_u.mutation.ResetPaidBy()
	_u.mutation.SetPaidBy(v)
	return _u
}

// SetNillablePaidBy sets the "paid_by" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillablePaidBy(v *int64) *ExpenseUpdate {
	if v != nil {
		_u.SetPaidBy(*v)
	}
	return _u
}

// AddPaidBy adds value to the "paid_by" field.
func (_u *ExpenseUpdate) AddPaidBy(v int64) *ExpenseUpdate {
	_u.mutation.AddPaidBy(v)
	return _u
}

// SetPaidByName sets the "paid_by_name" field.
func (_u *ExpenseUpdate) SetPaidByName(v string) *ExpenseUpdate {
	_u.mutation.SetPaidByName(v)
	return _u
}

// SetNillablePaidByName sets the "paid_by_name" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillablePaidByName(v *string) *ExpenseUpdate {
	if v != nil {
		_u.SetPaidByName(*v)
	}
	return _u
}

// SetForOther sets the "for_other" field.
func (_u *ExpenseUpdate) SetForOther(v bool) *ExpenseUpdate {
	_u.mutation.SetForOther(v)
	return _u
}

// SetNillableForOther sets the "for_other" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillableForOther(v *bool) *ExpenseUpdate {
	if v != nil {
		_u.SetForOther(*v)
	}
	return _u
}

// Mutation returns the ExpenseMutation object of the builder.
func (_u *ExpenseUpdate) Mutation() *ExpenseMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExpenseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExpenseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExpenseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExpenseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ExpenseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(expense.Table, expense.Columns, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(expense.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(expense.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(expense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(expense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(expense.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidBy(); ok {
		_spec.SetField(expense.FieldPaidBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaidBy(); ok {
		_spec.AddField(expense.FieldPaidBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaidByName(); ok {
		_spec.SetField(expense.FieldPaidByName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForOther(); ok {
		_spec.SetField(expense.FieldForOther, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{expense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExpenseUpdateOne is the builder for updating a single Expense entity.
type ExpenseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExpenseMutation
}

// SetChatID sets the "chat_id" field.
func (_u *ExpenseUpdateOne) SetChatID(v int64) *ExpenseUpdateOne {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillableChatID(v *int64) *ExpenseUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *ExpenseUpdateOne) AddChatID(v int64) *ExpenseUpdateOne {
	_u.mutation.AddChatID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ExpenseUpdateOne) SetAmount(v float64) *ExpenseUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillableAmount(v *float64) *ExpenseUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ExpenseUpdateOne) AddAmount(v float64) *ExpenseUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExpenseUpdateOne) SetDescription(v string) *ExpenseUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillableDescription(v *string) *ExpenseUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPaidBy sets the "paid_by" field.
func (_u *ExpenseUpdateOne) SetPaidBy(v int64) *ExpenseUpdateOne {
	_u.mutation.ResetPaidBy()
	_u.mutation.SetPaidBy(v)
	return _u
}

// SetNillablePaidBy sets the "paid_by" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillablePaidBy(v *int64) *ExpenseUpdateOne {
	if v != nil {
		_u.SetPaidBy(*v)
	}
	return _u
}

// AddPaidBy adds value to the "paid_by" field.
func (_u *ExpenseUpdateOne) AddPaidBy(v int64) *ExpenseUpdateOne {
	_u.mutation.AddPaidBy(v)
	return _u
}

// SetPaidByName sets the "paid_by_name" field.
func (_u *ExpenseUpdateOne) SetPaidByName(v string) *ExpenseUpdateOne {
	_u.mutation.SetPaidByName(v)
	return _u
}

// SetNillablePaidByName sets the "paid_by_name" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillablePaidByName(v *string) *ExpenseUpdateOne {
	if v != nil {
		_u.SetPaidByName(*v)
	}
	return _u
}

// SetForOther sets the "for_other" field.
func (_u *ExpenseUpdateOne) SetForOther(v bool) *ExpenseUpdateOne {
	_u.mutation.SetForOther(v)
	return _u
}

// SetNillableForOther sets the "for_other" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillableForOther(v *bool) *ExpenseUpdateOne {
	if v != nil {
		_u.SetForOther(*v)
	}
	return _u
}

// Mutation returns the ExpenseMutation object of the builder.
func (_u *ExpenseUpdateOne) Mutation() *ExpenseMutation {
	return _u.mutation
}

// Where appends a list predicates to the ExpenseUpdate builder.
func (_u *ExpenseUpdateOne) Where(ps ...predicate.Expense) *ExpenseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExpenseUpdateOne) Select(field string, fields ...string) *ExpenseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Expense entity.
func (_u *ExpenseUpdateOne) Save(ctx context.Context) (*Expense, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExpenseUpdateOne) SaveX(ctx context.Context) *Expense {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExpenseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExpenseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ExpenseUpdateOne) sqlSave(ctx context.Context) (_node *Expense, err error) {
	_spec := sqlgraph.NewUpdateSpec(expense.Table, expense.Columns, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Expense.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, expense.FieldID)
		for _, f := range fields {
			if !expense.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != expense.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(expense.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(expense.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(expense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(expense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(expense.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidBy(); ok {
		_spec.SetField(expense.FieldPaidBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaidBy(); ok {
		_spec.AddField(expense.FieldPaidBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaidByName(); ok {
		_spec.SetField(expense.FieldPaidByName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForOther(); ok {
		_spec.SetField(expense.FieldForOther, field.TypeBool, value)
	}
	_node = &Expense{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{expense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
