// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-buddy/ent/expense"
	"bill-buddy/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	expenseFields := schema.Expense{}.Fields()
	_ = expenseFields
	// expenseDescDescription is the schema descriptor for description field.
	expenseDescDescription := expenseFields[2].Descriptor()
	// expense.DefaultDescription holds the default value on creation for the description field.
	expense.DefaultDescription = expenseDescDescription.Default.(string)
	// expenseDescForOther is the schema descriptor for for_other field.
	expenseDescForOther := expenseFields[5].Descriptor()
	// expense.DefaultForOther holds the default value on creation for the for_other field.
	expense.DefaultForOther = expenseDescForOther.Default.(bool)
	// expenseDescCreatedAt is the schema descriptor for created_at field.
	expenseDescCreatedAt := expenseFields[6].Descriptor()
	// expense.DefaultCreatedAt holds the default value on creation for the created_at field.
	expense.DefaultCreatedAt = expenseDescCreatedAt.Default.(func() time.Time)
}
